<div class="footer-links">
	<?php
	// Footer product
	echo $block->getLayout()
		->createBlock('Magento\Cms\Block\Block')
		->setBlockId('footer-products-block')
		->toHtml();

	// Footer our difference
	echo $block->getLayout()
		->createBlock('Magento\Cms\Block\Block')
		->setBlockId('footer-our-difference-block')
		->toHtml();

	// Footer About
	echo $block->getLayout()
		->createBlock('Magento\Cms\Block\Block')
		->setBlockId('footer-about-block')
		->toHtml();

	// Footor customer service
	echo $block->getLayout()
		->createBlock('Magento\Cms\Block\Block')
		->setBlockId('footer-customer-service-block')
		->toHtml();

	// Footor customer service
	echo $block->getLayout()
		->createBlock('Magento\Cms\Block\Block')
		->setBlockId('footet-social-block')
		->toHtml();
	?>
</div>