<?php
echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('banner-slider-home')->toHtml();
?>

<script>
    require([
        'jquery',
        'slick'
    ], function($) {
        $(document).ready(function() {
            $(".banner-slider").slick({
                dots: true,
                autoplay: true,
                infinite: true,
                speed: 300,
                autoplaySpeed: 3500,
                slidesToShow: 1,
                slidesToScroll: 1
            });
        });
    });
</script>