<?php 
echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('favourites_product')->toHtml();
?>


<!-- script favourites -->
<script>
    require([
        'jquery',
        'slick'
    ], function($) {
        $(document).ready(function() {
            $(".widget-product-grid").slick({
                dots: true,
                autoplay: false,
                infinite: true,
                speed: 300,
                autoplaySpeed: 3500,
                slidesToShow: 3,
                slidesToScroll: 1
            });
        });
    });
</script>
<!-- script favourites -->