<?php 
echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('home-product')->toHtml();
?>


<!-- script favourites -->
<!-- <script>
    require([
        'jquery',
        'slick'
    ], function($) {
        $(document).ready(function() {
            $(".widget-product-grid").slick({
                dots: true,
                autoplay: false,
                infinite: true,
                speed: 300,
                autoplaySpeed: 3500,
                slidesToShow: 3,
                slidesToScroll: 1
            });
        });
    });
</script> -->
<!-- script favourites -->

<!-- <script type="text/javascript" xml="space">
    require([
        'jquery', 
        'owlcarousel'
    ], function($){ 
        $(document).ready(function() {
            $('.product-items ').owlCarousel({
                loop:false,
                nav:false,
                items:3,
                dots:true,
                autoplay:true,
                autoplayTimeout:3000
            })
        });
    });
</script> -->