<?php 
echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('home-product')->toHtml();
?>

<script type="text/javascript" xml="space">
    require([
        'jquery', 
        'owlcarousel'
    ], function($){ 
        $(document).ready(function() {
            $(".widget-product-grid").owlCarousel({
                loop:true,
                nav:true,
                items:3,
                dots:false,
                margin:20,
                autoplay:false,
                autoplayTimeout:3000,
                responsive:{
                    0:{
                        items:1,
                        nav:true
                    },
                    410:{
                        items:1.2,
                        nav:true
                    },
                    450:{
                        items:1.5,
                        nav:true
                    },
                    620:{
                        items:2,
                        nav:true
                    },
                    768:{
                        items:2.5,
                        nav:true
                    },
                    992:{
                        items:3,
                        nav:true,
                        loop:true
                    }
                }
            })
        });
    });
</script>