<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()) : ?>
    <div class="box-tocart">
        <div class="fieldset">
            <!-- <div class="field qty">
                <div class="control">
                    <span class="minus-btn qty-btn" onclick="this.nextElementSibling.value --"></span>
                    <input type="number" name="qty" maxlength="12" minlength="1" value="1" title="Qty" class="input-text qty" data-validate="null">
                    <span class="plus-btn qty-btn" onclick="this.previousElementSibling.value ++"></span>
                </div>
            </div> -->
            <?php if ($block->shouldRenderQuantity()) : ?>
                <!-- this is the code will override -->
                <div class="field qty">
                    <label class="label" for="qty"><span><?= $block->escapeHtml(__('Qty')) ?></span></label>
                    <div class="control">
                        <span class="minus-btn qty-btn"></span>
                        <input type="number" name="qty" id="qty" class="input-text qty" maxlength="12" value="<?= $block->getProductDefaultQty() * 1 ?>" title="<?= $block->escapeHtmlAttr(__('Qty')) ?>" class="input-text qty" data-validate="<?= $block->escapeHtmlAttr(json_encode($block->getQuantityValidators())) ?>" />
                        <span class="plus-btn qty-btn"></span>

                        <script type="text/javascript">
                            // this is the javascript code quantity
                            require(['jquery'], function($) {
                                $('.box-tocart .minus-btn').on('click', function() {
                                    var qty = parseInt($('#qty').val());
                                    qty = qty - 1;
                                    $('#qty').val(qty).trigger('change');
                                });
                                $('.box-tocart .plus-btn').on('click', function() {
                                    var qty = parseInt($('#qty').val());
                                    qty = qty + 1;
                                    $('#qty').val(qty).trigger('change');
                                });
                                $('#qty').on('change', function() {
                                    var qty = parseInt($(this).val());
                                    if (qty > 100) {
                                        $(this).val('100');
                                    } else if (qty < 1) {
                                        $(this).val('1');
                                    }
                                });
                            });
                        </script>
                    </div>
                </div>
                <div>
                </div>
            <?php endif; ?>
            <div class="actions">
                <button type="submit" title="<?= $block->escapeHtmlAttr($buttonTitle) ?>" class="action primary tocart" id="product-addtocart-button" disabled>
                    <span><?= $block->escapeHtml($buttonTitle) ?></span>
                </button>
                <?= $block->getChildHtml('', true) ?>
            </div>
        </div>
    </div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
        "Magento_Catalog/js/validate-product": {}
    }
}
</script>

