<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Update Cart'); ?>
<?php if ($_product->isSaleable()) : ?>
    <div class="box-tocart update">
        <fieldset class="fieldset">
            <?php if ($block->shouldRenderQuantity()) : ?>
                <div class="field qty">
                    <label class="label" for="qty"><span><?= $block->escapeHtml(__('Qty')) ?></span></label>
                    <div class="control">
                        <span class="minus">
                            <button type="button" title="<?= __('Reduce the quantity'); ?>">-</button>
                        </span>
                        <input type="number" name="qty" id="qty" min="0" value="" title="<?= $block->escapeHtmlAttr(__('Qty')) ?>" class="input-text qty" data-validate="<?= $block->escapeHtmlAttr(json_encode($block->getQuantityValidators())) ?>" />
                        <span class="plus"><button type="button" title="<?= __('Increase the quantity'); ?>">+</button></span>
                        <script type="text/javascript">
                            // this is the javascript code quantity
                            require(['jquery'], function($) {
                                $('.box-tocart .minus').on('click', function() {
                                    var qty = parseInt($('#qty').val());
                                    qty = qty - 1;
                                    $('#qty').val(qty).trigger('change');
                                });
                                $('.box-tocart .plus').on('click', function() {
                                    var qty = parseInt($('#qty').val());
                                    qty = qty + 1;
                                    $('#qty').val(qty).trigger('change');
                                });
                                $('#qty').on('change', function() {
                                    var qty = parseInt($(this).val());
                                    if (qty > 100) {
                                        $(this).val('100');
                                    } else if (qty < 1) {
                                        $(this).val('1');
                                    }
                                });
                            });
                        </script>
                    </div>
                </div>
            <?php endif; ?>
            <div class="actions">
                <button type="submit" title="<?= $block->escapeHtmlAttr($buttonTitle) ?>" class="action primary tocart" id="product-updatecart-button">
                    <span><?= $block->escapeHtml($buttonTitle) ?></span>
                </button>
                <?= $block->getChildHtml('', true) ?>
            </div>
        </fieldset>
    </div>
    <script type="text/x-magento-init">
        {
            "#product_addtocart_form": {
                "validation": {},
                "addToCart": {
                    "cartButtonId": "#product-updatecart-button",
                    "cartForm": "#product_addtocart_form"
                }
            }
        }
    </script>
<?php endif; ?>